const prTexts = [
  "Chef’s kiss, no crumbs 👨‍🍳",
  "Its giving ✨Tech Guru✨",
  "🚀",
  "Slaayy, gurl!! 💅💅",
  "Compiled? ate. 🍽️",
  "skrrt skrrt into prod 🏎️",
  "ok slay, I see you 🫶",
  "ate and left no bugs 🍽️",
  "not me approving this with tears in my eyes 😭",
  "it's giving senior dev energy 🧓✨",
  "she snapped with this one 🔥",
  "this code... poetic actually 📖",
  "lowkey flawless, highkey impressed 😮‍💨",
  "serving clean code realness 💅",
  "this commit has main character energy 🎬",
  "built like a baddie 💁‍♀️",
  "didn’t have to go this hard but you did 😤",
  "absolutely no notes 👏",
  "this PR walked so others could run 🏃‍♀️",
  "giving… ✨promotion-worthy✨",
  "i would trust this code with my life 💖",
  "you understood the assignment ✅",
  "this code made me believe in tech again 🌈",
  "not me approving instantly 😭",
];
