const prTexts = [
  "chef’s kiss, no crumbs 🤌",
  "its giving ✨tech guru✨",
  "yaaas gurl, slaayy!! 💅💅",
  "Compiled? ate. 🍽️",
  "skrrt skrrt into prod 🏎️",
  "ok slay, I see you 🫶",
  "ate and left no bugs 🍽️",
  "not me approving this with tears in my eyes 😭",
  "it's giving senior dev energy 🧓✨",
  "she snapped with this one 🔥",
  "this code... poetic actually 📖",
  "lowkey flawless, highkey impressed 😮‍💨",
  "serving clean code realness 💅",
  "this commit has main character energy 🎬",
  "built like a baddie 💁‍♀️",
  "didn’t have to go this hard but you did 😤",
  "absolutely no notes 👏",
  "this PR walked so others could run 🏃‍♀️",
  "giving… ✨promotion-worthy✨",
  "i would trust this code with my life 💖",
  "you understood the assignment ✅",
  "this code made me believe in tech again 🌈",
  "not me approving instantly 😭",
  "literally obsessed with this 🔥",
  "this? this is art 🎨",
  "wait why is this actually iconic 😭",
  "i gasped",
  "ok but why did this go so hard??? 💀",
  "this PR understood the vibes completely ✨",
  "emotionally attached to this diff now 🫂",
  "this code is in its reputation era 💅",
  "u kinda ate with this tbh 🍴",
  "10/10 would review again ⭐",
  "this diff just told a story 📚",
  "you dropped this 👑",
  "shooketh! 🙇",
  "lit 🔥",
  "periodt! 💅",
  "its bussin 🐝",
  "clean, efficient, AND dank?? ok flex 💪",
  "gg 🤝",
  "okurrr! 💅",
];
